### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JuzTosS** [PSDev/LicensesDialog#73]
Steps to reproduce
Do as fast as possible:
1. Press on a link at the license dialog
2. Press back button
3. Go to step 1

**Stacktrace:**
```
01-18 11:06:11.303: W/System.err(21533): java.lang.NullPointerException: uriString
01-18 11:06:11.313: W/System.err(21533): 	at android.net.Uri$StringUri.<init>(Uri.java:471)
01-18 11:06:11.313: W/System.err(21533): 	at android.net.Uri$StringUri.<init>(Uri.java:461)
01-18 11:06:11.313: W/System.err(21533): 	at android.net.Uri.parse(Uri.java:433)
01-18 11:06:11.313: W/System.err(21533): 	at de.psdev.licensesdialog.LicensesDialog$7.onCreateWindow(LicensesDialog.java:185)
01-18 11:06:11.313: W/System.err(21533): 	at com.android.webview.chromium.WebViewContentsClientAdapter.onCreateWindow(WebViewContentsClientAdapter.java:402)
01-18 11:06:11.313: W/System.err(21533): 	at org.chromium.android_webview.AwWebContentsDelegateAdapter.addNewContents(AwWebContentsDelegateAdapter.java:241)
01-18 11:06:11.313: W/System.err(21533): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-18 11:06:11.313: W/System.err(21533): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
01-18 11:06:11.313: W/System.err(21533): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-18 11:06:11.313: W/System.err(21533): 	at android.os.Looper.loop(Looper.java:145)
01-18 11:06:11.313: W/System.err(21533): 	at android.app.ActivityThread.main(ActivityThread.java:6837)
01-18 11:06:11.313: W/System.err(21533): 	at java.lang.reflect.Method.invoke(Native Method)
01-18 11:06:11.313: W/System.err(21533): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-18 11:06:11.313: W/System.err(21533): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
01-18 11:06:11.313: W/System.err(21533): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
01-18 11:06:11.313: A/chromium(21533): [FATAL:jni_android.cc(295)] Check failed: false. Please include Java exception stack in crash report```

**Comment by kaiwinter** [comment]
Seems to be fixed on the master branch. But there is no release after this bugfix (https://github.com/PSDev/LicensesDialog/commit/96cda2e77f9868eaa26c904e0d411ae92038bb5c).

**Comment by hameno** [comment]
Sorry, did not have time yet to release it. You can use the snapshots until then: https://oss.sonatype.org/content/repositories/snapshots/de/psdev/licensesdialog/library/1.8.2-SNAPSHOT/

**Comment by JuzTosS** [comment]
Thanks! Will wait for the release!
