### ISSUE TITLE
How to Give Credit to Icon Designer

### ISSUE THREAD

**Issue by 1Kamal1** [PSDev/LicensesDialog#87]
Can anyone tell me how to give Credit to Designer of the Icon with Website Link 
For Example = 
Icons made by ** Designed by Freepik** from [http://www.freepik.com/](url) is licensed by [https://creativecommons.org/licenses/by/3.0/](url) 
Any help will be Appreciated
Thanks

**Comment by personaljesusua** [comment]
I did it like this:

    <notice>
        <name>Watermelon hand drawn fruit piece By Agata Kuczminska</name>
        <url>https://www.flaticon.com/free-icon/watermelon-hand-drawn-fruit-piece_53691</url>
        <license>Creative Commons Attribution 3.0 Unported</license>
    </notice>

**Comment by 1Kamal1** [comment]
Are you Using it as Icon or normal image

**Comment by personaljesusua** [comment]
I'm using it for launcher icon

**Comment by 1Kamal1** [comment]
Edit
Have you launched your app recently?
if yes then Send me the link
because I want to ensure that is it accepted by Google or not?

**Comment by personaljesusua** [comment]
@1Kamal1, I haven't published app yet. But why do you think Google won't accept it? License grant me permission to use icon. Also this icon isn't some brand logo.

**Comment by 1Kamal1** [comment]
I got this exception

E/UncaughtException: java.lang.IllegalStateException: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @21:110 in java.io.InputStreamReader@ec325e2) 
        at de.psdev.licensesdialog.LicensesDialog.getNotices(LicensesDialog.java:205)
        at de.psdev.licensesdialog.LicensesDialog.access$500(LicensesDialog.java:39)
        at de.psdev.licensesdialog.LicensesDialog$Builder.build(LicensesDialog.java:345)
        at com.example.kamalverma.final_project.Drawer.About_fragment$2.onClick(About_fragment.java:48)
        at android.view.View.performClick(View.java:5706)
        at android.view.View$PerformClick.run(View.java:22834)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6339)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
     Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @21:110 in java.io.InputStreamReader@ec325e2) 
        at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
        at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at de.psdev.licensesdialog.NoticesXmlParser.readText(NoticesXmlParser.java:118)
        at de.psdev.licensesdialog.NoticesXmlParser.readTag(NoticesXmlParser.java:111)
        at de.psdev.licensesdialog.NoticesXmlParser.readUrl(NoticesXmlParser.java:97)
        at de.psdev.licensesdialog.NoticesXmlParser.readNotice(NoticesXmlParser.java:80)
        at de.psdev.licensesdialog.NoticesXmlParser.parse(NoticesXmlParser.java:57)
        at de.psdev.licensesdialog.NoticesXmlParser.parse(NoticesXmlParser.java:41)
        at de.psdev.licensesdialog.LicensesDialog.getNotices(LicensesDialog.java:199)
        at de.psdev.licensesdialog.LicensesDialog.access$500(LicensesDialog.java:39) 
        at de.psdev.licensesdialog.LicensesDialog$Builder.build(LicensesDialog.java:345) 
        at com.example.kamalverma.final_project.Drawer.About_fragment$2.onClick(About_fragment.java:48) 
        at android.view.View.performClick(View.java:5706) 
        at android.view.View$PerformClick.run(View.java:22834) 
        at android.os.Handler.handleCallback(Handler.java:836) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6339) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by 1Kamal1** [comment]
Thanks @personaljesusua  it works
