### ISSUE TITLE
Resources$NotFoundException on Google Play console pre-launch report

### ISSUE THREAD

**Issue by er-mo** [PSDev/LicensesDialog#98]
Screen Size: 720 × 1280
Screen Density (dpi): 320
Model Name: P8 Lite
RAM: 2048 MB
Manufacturer: Huawei
OpenGL ES Version: 2.0
Android Version: Android 5.0
Native Platform: armeabi-v7a
Locale: en_US
CPU Make: HiSilicon
CPU Model: Hi6220

Stacktrace:
`
 FATAL EXCEPTION: ControllerMessenger
Process PID: 18867
android.content.res.Resources$NotFoundException: String resource ID #0x3040002
	at android.content.res.HwResources.getText(HwResources.java:1252)
	at android.content.res.Resources.getString(Resources.java:374)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:948)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:848)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:788)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:635)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:573)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:315)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:100)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:267)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:127)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:114)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:111)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:264)
	at android.webkit.WebView.<init>(WebView.java:548)
	at android.webkit.WebView.<init>(WebView.java:483)
	at android.webkit.WebView.<init>(WebView.java:466)
	at android.webkit.WebView.<init>(WebView.java:453)
	at android.webkit.WebView.<init>(WebView.java:443)
	at de.psdev.licensesdialog.LicensesDialog.createWebView(LicensesDialog.java:178)
	at de.psdev.licensesdialog.LicensesDialog.create(LicensesDialog.java:79)
	at de.psdev.licensesdialog.LicensesDialog.show(LicensesDialog.java:162)`

**Comment by hameno** [comment]
Thanks for the report. I'm not sure if the library if really the cause of this error. Can you please try and find the string resource behind #0x3040002 ? I think you can you the APK analyzer in Android Studio with your APK.

**Comment by er-mo** [comment]
You are probably right. I was not able to locate that resource.

**Comment by ziSo12** [comment]
Getting the same error, also with this library on Android 5.0 pre-launch report
Issue: android.content.res.Resources$NotFoundException: String resource ID #0x3040002

Test ID

1
Screen Size

720 × 1280
Test Duration

300 seconds
Screen Density (dpi)
320
Model Name
P8 Lite
RAM
2048 MB
Manufacturer
Huawei
OpenGL ES Version
2.0
Android Version
Android 5.0
Native Platform
armeabi-v7a
Locale
en_US
CPU Make
HiSilicon
CPU Model
Hi6220

Seems the library is using this value somehow but it can't be found.

**Comment by pavelaizen** [comment]
**Device: Huawei Y6 TIT-AL00**
```
 android.content.res.Resources$NotFoundException: String resource ID #0x3040003
	at android.content.res.HwResources.getText(HwResources.java:1287)
	at android.content.res.Resources.getString(Resources.java:431)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:709)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:633)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:685)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:834)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:670)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:605)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
	at android.webkit.WebView.<init>(WebView.java:597)
	at android.webkit.WebView.<init>(WebView.java:531)
	at android.webkit.WebView.<init>(WebView.java:514)
	at android.webkit.WebView.<init>(WebView.java:501)
	at android.webkit.WebView.<init>(WebView.java:491)
```

**Comment by hameno** [comment]
Unless this happens on a real device and can ve reproduced I'm not gonna investigate further. Please comment if this is somehow reproducible on a real device.

**Comment by luke40** [comment]
> Screen Size: 720 × 1280
> Screen Density (dpi): 320
> Model Name: P8 Lite
> RAM: 2048 MB
> Manufacturer: Huawei
> OpenGL ES Version: 2.0
> Android Version: Android 5.0
> Native Platform: armeabi-v7a
> Locale: en_US
> CPU Make: HiSilicon
> CPU Model: Hi6220
> 
> Stacktrace:
> ` FATAL EXCEPTION: ControllerMessenger Process PID: 18867 android.content.res.Resources$NotFoundException: String resource ID #0x3040002 at android.content.res.HwResources.getText(HwResources.java:1252) at android.content.res.Resources.getString(Resources.java:374) at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:948) at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:848) at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649) at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:788) at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:635) at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:573) at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:315) at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:100) at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:267) at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:127) at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:114) at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144) at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:111) at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:264) at android.webkit.WebView.<init>(WebView.java:548) at android.webkit.WebView.<init>(WebView.java:483) at android.webkit.WebView.<init>(WebView.java:466) at android.webkit.WebView.<init>(WebView.java:453) at android.webkit.WebView.<init>(WebView.java:443) at de.psdev.licensesdialog.LicensesDialog.createWebView(LicensesDialog.java:178) at de.psdev.licensesdialog.LicensesDialog.create(LicensesDialog.java:79) at de.psdev.licensesdialog.LicensesDialog.show(LicensesDialog.java:162)`

**Comment by hameno** [comment]
This seems to be a bug with appcompat 1.1.0: https://issuetracker.google.com/issues/141132133
It is not caused by this library, and as such I'm going to lock this thread now.
